TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += circle.db
DB += dbExample1.db
DB += dbExample2.db
DB += PSVersion.db
DB += dbSubExample.db
DB += user.substitutions
DB += PS.db
DB += CurrentPS.db
DB += dbExtratorHV.db
DB += digitalRampingPSInt.db
DB += dbPSRampingInfo.db
DB += digitalPSInt.db
DB += dbui.db
DB += DigitalBumpPS.db
DB += digitalDCPSInt.db
DB += digitalScanPSInt.db
DB += dbDPRAMwv.db
DB += dbAPMPS.db
DB += dbHarmonicPSsoft.db
DB += ramping_ps.substitutions
DB += dc_ethernet_ps.substitutions
DB += dc_serial_ps.substitutions
DB += dbRampingPS.db
DB += dbDigitalDCEthernetPS.db
DB += dbDigitalDCSerialPS.db
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

